-- CREATE THE DATABASE	
CREATE DATABASE LogisticsdB;

-- USE THE DATABASE CREATED
USE LogisticsdB;

-- 1) CREATE THE Employee_Details TABLE
CREATE TABLE Employee_Details(
Emp_ID INT PRIMARY KEY CHECK (Emp_ID < 100000), --check condition since INT won't take parameters
Emp_NAME VARCHAR(30) ,
Emp_BRANCH VARCHAR(15) ,
Emp_DESIGNATION VARCHAR (40) ,
Emp_ADDR VARCHAR (100) ,
Emp_CONT_NO VARCHAR (10) 
) ;

-- 2) CREATING THE Membership_Table
CREATE TABLE Membership_Table (
M_ID INT PRIMARY KEY,
START_DATE TEXT,
END_DATE TEXT
) ;

-- 3) CREATING THE Customer_Table

CREATE TABLE Customer_Table (
Cust_ID INT PRIMARY KEY,
Cust_NAME VARCHAR (30),
Cust_EMAIL_ID VARCHAR (50),
Cust_CONT_NO VARCHAR (10),
Cust_ADDR VARCHAR (100),
Cust_TYPE VARCHAR (30) CHECK (Cust_TYPE IN ('Wholesale','Retail','Internal Goods')), -- THE COLUMN TAKES ONLY THESE VALUES
Membership_M_ID INT FOREIGN KEY REFERENCES Membership_Table(M_ID)
) ;

--  4) CREATE THE Payment_Details TABLE --  THIS CAN BE RUN ONLY AFTER THE SHIPMENT_TABLE CREATION AS IT REFERENCES FOREING KEY
CREATE TABLE Payment_Details (
PAYMENT_ID VARCHAR(40) PRIMARY KEY,
AMOUNT INT,
PAYMENT_STATUS VARCHAR(10) CHECK (PAYMENT_STATUS IN ('Paid','Not Paid')), -- THIS COLUMN ONLY TAKES THESE TWO VALUES
PAYMENT_DATE TEXT,
PAYMENT_MODE VARCHAR(25) CHECK (PAYMENT_MODE IN ('COD','Card Payment')), -- THIS COLUMN ONLY TAKES THESE TWO VLAUES
Shipment_SH_ID VARCHAR (6) FOREIGN KEY REFERENCES Shipment_Details(SD_ID),
Shipment_Client_C_ID INT FOREIGN KEY REFERENCES Customer_Table(Cust_ID)
);

-- 5) CREATE THE Shipment_Details TABLE
CREATE TABLE Shipment_Details (
SD_ID VARCHAR(6) PRIMARY KEY,
SD_CONTENT VARCHAR(40),
SD_DOMAIN VARCHAR(15) CHECK (SD_DOMAIN IN ('International','Domestic')),  -- THIS COLUMN ONLY TAKES THESE TWO VLAUES
SD_TYPE VARCHAR (15) CHECK (SD_TYPE IN ('Express','Regular')),  -- THIS COLUMN ONLY TAKES THESE TWO VLAUES
SD_WEIGHT VARCHAR (10),
SD_CHARGES INT,
SD_ADDR VARCHAR(100),
DS_ADDR VARCHAR(100),
Customer_Cust_ID INT FOREIGN KEY REFERENCES Customer_Table(Cust_ID)
) ; 

-- 6) CREATE THE STATUS TABLE
CREATE TABLE Status_Table (
CURRENT_ST VARCHAR(15),
SENT_DATE TEXT ,
DELIVERY_DATE TEXT ,
SH_ID VARCHAR(6) PRIMARY KEY
);

-- 7) CREATE TABLE Employee_Manages_Shipment_Table
CREATE TABLE Employee_Manages_Shipment_Table (
Employee_E_ID INT FOREIGN KEY REFERENCES Employee_Details(Emp_ID),
Shipment_SH_ID VARCHAR(6) FOREIGN KEY REFERENCES Shipment_Details(SD_ID),
Status_SH_ID VARCHAR (6) FOREIGN KEY REFERENCES Status_Table(SH_ID)
);


